name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: yarn install dependencies
      run: yarn --frozen-lockfile
      env:
        CI: true
    - name: yarn build files
      run: yarn build
      env:
        CI: true
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: static_files
        # Directory containing files to upload
        path: build
