name: Node CI

on: 
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: yarn install dependencies
      run: yarn --frozen-lockfile
      env:
        CI: true
    - name: yarn pack 
      run: cd build;yarn pack -f wissenschaftstag-anmeldung.tgz
      env:
        CI: true
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: static_files
        # Directory containing files to upload
        path: build
    - name: GH Pages deploy
      uses: Cecilapp/GitHub-Pages-deploy@2.0.0
      env:
        EMAIL: robin.marchart@hotmail.com               
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: build/
